# Generated by Django 2.2 on 2019-12-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='dummy-post'),
            preserve_default=False,
        ),
    ]
